pw: improve readme and add note on git-pw version
Older git-pw versions have some mbox decoding issues which I ran into,
but this got fixed in a more recent version, therefore add a note to
the README:

  $ git pw series download 133745 mbox.i
  Server version missing
  You should provide the server version in the URL configured via git-config or --server
  This will be required in git-pw 2.0
  Traceback (most recent call last):
  File "/usr/bin/git-pw", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/git_pw/series.py", line 55, in download_cmd
    output.write(api.get(series['mbox']).text)
  UnicodeEncodeError: 'ascii' codec can't encode characters in position 4418-4420: ordinal not in range(128)

Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>